// File generated by FlutterFire CLI.
// To resolve the 'Undefined name' error properly, run: flutterfire configure
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwZmwvyX82UfeOWI_aaa2VSU-0-XaA3Eo',
    appId: '1:1063596716078:web:3dbc7808dbf3f93211afbf',
    messagingSenderId: '1063596716078',
    projectId: 'mentor-94682',
    authDomain: 'mentor-94682.firebaseapp.com',
    storageBucket: 'mentor-94682.firebasestorage.app',
    measurementId: 'G-T64WP0QEGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3DC8UOIHfy7nBcnFP1CDDXRuXJuOKCH4',
    appId: '1:1063596716078:android:b6820f72b824f86011afbf',
    messagingSenderId: '1063596716078',
    projectId: 'mentor-94682',
    storageBucket: 'mentor-94682.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYZJskvyMLmZL4LNMuQL5aOCki_k_x5cg',
    appId: '1:1063596716078:ios:e63cd864b6a5497211afbf',
    messagingSenderId: '1063596716078',
    projectId: 'mentor-94682',
    storageBucket: 'mentor-94682.firebasestorage.app',
    iosClientId: '1063596716078-vh71q1ndn5iq46v99dc5eun1fndig4vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentor',
  );

}